#!/usr/bin/env python3
import requests
import sys
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
ARDUINO_SNIPPETS = [
    ROOT / "arduino" / "RFID_Bambu_lab_reader" / "generated" / "materials_snippet.h",
    ROOT / "arduino" / "RFID_Bambu_lab_reader_OLED" / "generated" / "materials_snippet.h",
]

def esc(val):
    if not val:
        return ""
    return (
        str(val)
        .encode("ascii", "ignore")
        .decode("ascii")
        .replace("\\", "\\\\")
        .replace('"', '\\"')
    )

import re
def fetch_materials():
    readme_path = ROOT / "READMEqueen.md"
    lines = readme_path.read_text(encoding="utf-8").splitlines()
    materials = []
    current_category = None
    for line in lines:
        if line.startswith('#### '):
            current_category = line[5:].strip()
        # Match table rows, skip header and separator lines
        elif line.strip().startswith('|') and not re.match(r'^\|\s*[-: ]+\|', line):
            parts = [p.strip() for p in line.strip('|').split('|')]
            # Expect: Color | Filament Code | Variant ID | Status
            if len(parts) >= 4 and parts[1].isdigit():
                color = parts[0]
                code = parts[1]
                variant = parts[2]
                # fallback: if variant is missing or '?', use blank
                variant = variant if variant and variant != '?' else ''
                materialId = variant.split('-')[0] if '-' in variant and len(variant.split('-')[0]) > 0 else ''
                name = current_category or ''
                productUrl = ''
                materials.append({
                    'materialId': materialId,
                    'variantId': variant,
                    'filamentCode': code,
                    'name': name,
                    'color': color,
                    'productUrl': productUrl
                })
    return materials

def build_lines(materials):
    lines = [
        '// Generated by scripts/generate_material_snippets.py from Bambu-Lab-RFID-Library repo.',
        '// materialId, variantId, code, name, color, productUrl.',
    ]
    for m in materials:
        lines.append(f'    {{"{esc(m["materialId"])}", "{esc(m["variantId"])}", "{esc(m["filamentCode"])}", "{esc(m["name"])}", "{esc(m["color"])}", "{esc(m["productUrl"])}"}},')
    return lines

def write_snippets(lines):
    content = "\n".join(lines) + "\n"
    for path in ARDUINO_SNIPPETS:
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(content, encoding="utf-8")
        print(f"Wrote Arduino snippet: {path.relative_to(ROOT)}")

def main():
    materials = fetch_materials()
    if not materials:
        print("ERROR: No materials scraped.", file=sys.stderr)
        return 1
    lines = build_lines(materials)
    write_snippets(lines)
    return 0

if __name__ == "__main__":
    raise SystemExit(main())